### ISSUE TITLE
Add back To Top button

### ISSUE THREAD

**Issue by lewisushindi** [lewisushindi/little-kids-pre-school-website#2]
Add back to top arrow button  that will allow users to go back on top of the page automatically

**Comment by sairevanth0007** [comment]
Hello @lewisushindi ,

you can do it by creating a button in HTML files like this:
    <button onclick="topFunction()" id="scrolltop" >&#11165;</button>

and add JS code in script.js like this:
let mybutton = document.getElementById("scrolltop");
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}

I made the changes and a pull request. Go through it.

**Comment by lewisushindi** [comment]
@sairevanth0007  thank you have gone through the changes and merged your pull request. Thank you for contributing to this project !
